### ISSUE TITLE
Integration with YCM

### ISSUE THREAD

**Issue by Bietola** [calviken/vim-gdscript3#6]
Is there any chance that this plugin will work along with Valoric's YouCompleMe plugin? I know that YCM supports completers working with vim's omnicomplete functionality (which, from what I understood, is what this plugin uses under the hood), but I don't actually know how I would make the two things work together.

**Comment by calviken** [comment]
This seems to work: (add it to your vim config file)

```
if !exists('g:ycm_semantic_triggers')
    let g:ycm_semantic_triggers = {}
endif
let g:ycm_semantic_triggers.gdscript3 = [
    \'re!\w+',
    \'.',
    \'re!\bextends\s+',
    \'re!\bexport\(',
    \'re!\bfunc\s+',
    \'re!"res://[^"]*'
    \]
```

Only (minor) problem is that the items appear in strictly alphabetical order instead of being grouped by subclass. As far as I can tell, there's no way to disable YCM's sorting.

YCM:

![1](https://user-images.githubusercontent.com/8335373/42968651-88f27c2e-8b69-11e8-91cc-189ac964a9a0.png)

Regular completion:

![2](https://user-images.githubusercontent.com/8335373/42968515-1843258c-8b69-11e8-9971-df3b32cb4cce.png)

**Comment by Bietola** [comment]
It worked! Thanks for the quick response. As for the ordering, I don't see it as much of a problem for now... I'll see if I can get back to it from the other side (YCM's github) if starts to annoy me too much.
